// Aşağıdaki programın ekran çıktısı ne olur ?

#include <stdio.h>

int main(void)
{
	int x = 999; // x object has been initialized with value of 999.

	printf("%d\n", printf("%d", printf("%d", ++x)));

	// printf (print format[formatted output]) as a function, returns how many printable character it has printed. Usually its return value is discarded.
	// Evaluation order goes like this: printf("%d\n", printf("%d", printf("%d", ++x))) -> printf("%d\n", printf("%d", *firstnestedprintf*)) -> printf("%d\n", *secondnestedprintf*);
	
	// Inside first printf, prints the value as 1000. 
	// Because using a pre-increment operator while incrementing an object inside print function causes to print function to print the incremented version of object first and then does the actual incrementation.
	
	// Second printf, prints the return value of first evaluated printf and since 1 0 0 0 are 4 characters, it prints 4.

	//Third printf, prints the return value of second evaluated printf and since 4 is just 1 character it prints 1.

	//Overall output, since there are no escape characters, looks like this: "100041" -> 1000(value generated by expr '++x') | 4(characters '1000' of first printf) | 1(character '4' of second printf)
	
}
